services:
  postgres:
    image: postgres:16-alpine
    container_name: chat-postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/chat-postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/chat-postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ginuser
      POSTGRES_PASSWORD: ginpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: chatapp
    hostname: postgres
    restart: always
    user: root

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: gin@example.com
      PGADMIN_DEFAULT_PASSWORD: ginpassword
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres